# Generated by Django 3.2.7 on 2022-01-04 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='formatFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formRab', models.FileField(blank=True, upload_to='')),
                ('formFile', models.FileField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Instansi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instansi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='None', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ketProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nim', models.CharField(max_length=50)),
                ('jurusan', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=50)),
                ('noHP', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('judul', models.CharField(max_length=50)),
                ('tujuan', models.TextField(max_length=1200)),
                ('tanggal_pelaksanaan', models.DateField(blank=True, null=True)),
                ('waktu_pelaksanaan', models.CharField(default='', max_length=50)),
                ('lokasi_pelaksanaan', models.CharField(default='', max_length=50)),
                ('rab', models.FileField(blank=True, upload_to='')),
                ('file_proposal', models.FileField(blank=True, upload_to='')),
                ('asal_instansi', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='instansi_asal', to='proposalapps.instansi')),
                ('keterangan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_status', to='proposalapps.status')),
            ],
        ),
    ]
