# Generated by Django 3.2.7 on 2021-12-01 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketproposal',
            name='nim',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ketproposal',
            name='noHP',
            field=models.CharField(max_length=50),
        ),
    ]
