# Generated by Django 3.2.7 on 2021-11-30 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='asal_instansi',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
