# Generated by Django 3.2.7 on 2022-01-04 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instansi',
            name='instansi',
            field=models.CharField(default='', max_length=20),
        ),
    ]
