# Generated by Django 3.2 on 2022-01-10 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapps', '0002_alter_ketproposal_tujuan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketproposal',
            name='file_proposal',
            field=models.FileField(blank=True, upload_to='proposal'),
        ),
        migrations.AlterField(
            model_name='ketproposal',
            name='rab',
            field=models.FileField(blank=True, upload_to='rab'),
        ),
    ]
