# Generated by Django 3.2.7 on 2022-01-04 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapps', '0002_alter_instansi_instansi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instansi',
            name='instansi',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ketproposal',
            name='asal_instansi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='instansi_asal', to='proposalapps.instansi'),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
