# Generated by Django 3.2.7 on 2021-12-01 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapps', '0002_auto_20211201_1820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketproposal',
            name='jurusan',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='ketproposal',
            name='semester',
            field=models.IntegerField(default=1),
        ),
    ]
