# Generated by Django 3.2.7 on 2022-01-05 02:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapps', '0003_auto_20220104_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketproposal',
            name='keterangan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='proposal_status', to='proposalapps.status'),
        ),
    ]
