# Generated by Django 3.2.7 on 2021-12-02 03:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapps', '0003_auto_20211201_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ketproposal',
            name='semester',
            field=models.CharField(max_length=50),
        ),
    ]
