# Generated by Django 3.2 on 2022-01-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapps', '0003_auto_20220110_1005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatfile',
            name='formFile',
            field=models.FileField(blank=True, upload_to='file_tamplate'),
        ),
        migrations.AlterField(
            model_name='formatfile',
            name='formRab',
            field=models.FileField(blank=True, upload_to='file_tamplate'),
        ),
    ]
