# Generated by Django 3.2.7 on 2022-01-05 04:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proposalapps', '0004_alter_ketproposal_keterangan'),
    ]

    operations = [
        migrations.AddField(
            model_name='ketproposal',
            name='published1',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ketproposal',
            name='updated1',
            field=models.TimeField(auto_now=True),
        ),
    ]
