# Generated by Django 3.2.7 on 2021-11-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='dataUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=50)),
                ('nim', models.IntegerField(max_length=11)),
                ('jurusan', models.CharField(choices=[('Teknik Elektro', 'Teknik Elektro'), ('Teknik Informatika', 'Teknik Informatika'), ('Teknik Industri', 'Teknik Industri'), ('Sistem Informasi', 'Sistem Informasi'), ('Matematika', 'Matematika')], default='Teknik Elektro', max_length=20)),
                ('semester', models.IntegerField(max_length=2)),
                ('noHP', models.IntegerField(max_length=12)),
            ],
        ),
        migrations.CreateModel(
            name='ketProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul', models.CharField(max_length=50)),
                ('tujuan', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='rabProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rab', models.FileField(blank=True, upload_to='')),
            ],
        ),
    ]
