# Generated by Django 3.2.7 on 2021-11-26 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datauser',
            name='nim',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='noHP',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='datauser',
            name='semester',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5), (6, 6), (7, 7), (8, 8), (9, 9), (10, 10), (11, 11), (12, 12), (13, 13), (14, 14)], default=1),
        ),
    ]
